allow_remote_control yes

enabled_layouts tall:bias=50;full_size=1;mirrored=false,fat:bias=50;full_size=1;mirrored=false,stack,grid,horizontal,stack,vertical

font_family       JetBrainsMono Nerd Font Mono
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         16.0
url_style         straight
mouse_hide_wait   -1

cursor                none
cursor_shape          beam
cursor_blink_interval 0
window_padding_width  10

confirm_os_window_close            0
copy_on_select                     clipboard
enable_audio_bell                  no
hide_window_decorations            yes
macos_quit_when_last_window_closed yes
scrollback_pager                   bat

clear_all_shortcuts no

map cmd+enter launch --cwd=current --location=first

map alt+ctrl+cmd+escape       kitty_shell window
map alt+ctrl+cmd+shift+escape kitty_shell tab

map alt+ctrl+cmd+1 goto_tab 1
map alt+ctrl+cmd+2 goto_tab 2
map alt+ctrl+cmd+3 goto_tab 3
map alt+ctrl+cmd+4 goto_tab 4

map alt+ctrl+cmd+f4      detach_window ask
map alt+ctrl+cmd+shif+f4 detach_tab    ask

map alt+ctrl+cmd+[ layout_action decrease_num_full_size_windows
map alt+ctrl+cmd+] layout_action increase_num_full_size_windows
map alt+ctrl+cmd+/ layout_action mirror toggle

map alt+ctrl+cmd+left  resize_window narrower
map alt+ctrl+cmd+right resize_window wider
map alt+ctrl+cmd+up    resize_window taller
map alt+ctrl+cmd+down  resize_window shorter

map alt+ctrl+cmd+c       clear_terminal scroll active
map alt+ctrl+cmd+shift+c clear_terminal scroll all
map alt+ctrl+cmd+e       kitten hints --type hyperlink
map alt+ctrl+cmd+h       kitten hints --type hash --program -
map alt+ctrl+cmd+j       select_tab
map alt+ctrl+cmd+p       kitten hints --type path --program -
map alt+ctrl+cmd+shift+p kitten hints --type path
map alt+ctrl+cmd+r       last_used_layout
map alt+ctrl+cmd+shift+r resize_window reset
map alt+ctrl+cmd+s       launch --stdin-source=@screen_scrollback --type=overlay bat
map alt+ctrl+cmd+shift+s kitten kitty_grab/grab.py
map alt+ctrl+cmd+t       new_tab_with_cwd !neighbor
map alt+ctrl+cmd+shif+t  new_tab_with_cwd
map alt+ctrl+cmd+q       close_other_windows_in_tab
map alt+ctrl+cmd+w       kitten hints --type word --program -
map alt+ctrl+cmd+shift+w kitten hints --type line --program -
map alt+ctrl+cmd+z       toggle_layout stack
map alt+ctrl+cmd+shift+z toggle_layout tall

include base16-tomorrow-night.conf
