git clone https://github.com/catppuccin/alfred
git clone https://github.com/catppuccin/bat
git clone https://github.com/catppuccin/chrome
git clone https://github.com/catppuccin/emacs
git clone https://github.com/catppuccin/fzf
git clone https://github.com/catppuccin/k9s
git clone https://github.com/catppuccin/lazygit
git clone https://github.com/catppuccin/slack
git clone https://github.com/catppuccin/starship
git clone https://github.com/catppuccin/vimium
