"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

[aws]
disabled = true

[docker_context]
disabled = true

[elixir]
format = 'via [$symbol($version on  $otp_version )]($style)'
symbol = ' '

[git_branch]
style = 'bold green'
truncation_length = 12

[lua]
symbol = ' '

[nodejs]
disabled = true

[package]
disabled = true

[ruby]
symbol = ' '

[rust]
symbol = ' '
