ln -sf ~/dev/dot-files/.gitconfig ~/.gitconfig
ln -sf ~/dev/dot-files/.irbrc ~/.irbrc
ln -sf ~/dev/dot-files/starship.toml ~/.config/starship.toml
ln -sf ~/dev/dot-files/bat/config ~/.config/bat/config
ln -sf ~/dev/dot-files/bat/themes/Catppuccin-mocha.tmTheme ~/.config/bat/themes/Catppuccin-mocha.tmTheme
ln -sf ~/dev/dot-files/colorls/dark_colors.yaml ~/.config/colorls/dark_colors.yaml
ln -sf ~/dev/dot-files/doom-emacs/config.el ~/.doom.d/config.el
ln -sf ~/dev/dot-files/doom-emacs/init.el ~/.doom.d/init.el
ln -sf ~/dev/dot-files/doom-emacs/package.el ~/.doom.d/package.el
ln -sf ~/dev/dot-files/fish/config.fish ~/.config/fish/config.fish
ln -sf ~/dev/dot-files/fish/functions/abbreviations.fish  ~/.config/fish/functions/abbreviations.fish
ln -sf ~/dev/dot-files/fish/functions/fish_greeting.fish ~/.config/fish/functions/fish_greeting.fish
ln -sf ~/dev/dot-files/fish/functions/fish_user_key_bindings.fish ~/.config/fish/functions/fish_user_key_bindings.fish
ln -sf ~/dev/dot-files/helix/config.toml ~/.config/helix/config.toml
ln -sf ~/dev/dot-files/k9s/skin.yml  ~/.config/k9s/skin.yml
ln -sf ~/dev/dot-files/kitty/Catppuccin-Mocha.conf  ~/.config/kitty/Catppuccin-Mocha.conf
ln -sf ~/dev/dot-files/kitty/kitty.conf ~/.config/kitty/kitty.conf
ln -sf ~/dev/dot-files/kitty/macos-launch-services-cmdline ~/.config/kitty/macos-launch-services-cmdline
ln -sf ~/dev/dot-files/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
ln -sf ~/dev/dot-files/mc/ini ~/.config/mc/ini
ln -sf ~/dev/dot-files/vifm/vifmrc ~/.config/vifm/vifmrc
