theme = "catppuccin_mocha"

[editor]
auto-completion           = true
auto-format               = true
auto-info                 = true
auto-pairs                = false
auto-save                 = true
bufferline                = "never"
color-modes               = false
completion-replace        = true
completion-trigger-len    = 4
continue-comments         = false
cursorcolumn              = true
cursorline                = true
end-of-line-diagnostics   = "disable"
idle-timeout              = 400
indent-heuristic          = "tree-sitter"
jump-label-alphabet       = "ntesirlpufywhdcxmgoakvqzjb"
line-number               = "relative"
popup-border              = "all"
preview-completion-insert = true
rulers                    = [120]
scroll-lines              = 2
shell                     = ["fish", "-c"]
text-width                = 400
undercurl                 = false

# [editor.auto-pairs]
# "'" = "'"
# "(" = ")"
# "<" = ">"
# "[" = "]"
# "`" = "`"
# "{" = "}"
# '"' = '"'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
character   = "|"
render      = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line     = "disable"
max-diagnostics = 10
max-wrap        = 20
other-lines     = "disable"
prefix-len      = 1

[editor.lsp]
display-inlay-hints       = false
display-messages	        = false
display-progress-messages = true

[editor.smart-tab]
enable         = false
supersede-menu = false

[editor.soft-wrap]
enable             = false
max-indent-retain  = 40
max-wrap           = 20
wrap-at-text-width = true
wrap-indicator     = "↪"

[editor.statusline]
left      = ["file-modification-indicator", "file-name", "file-type"] 
center    = ["spinner", "mode", "spacer", "selections", "primary-selection-length",
                    "spacer", "separator", "spacer", "position", "position-percentage", "total-line-numbers"]
right     = ["register", "spacer"]
separator = "󰚄"

[editor.statusline.mode]
insert = ""
normal = "󱃱"
select = ""

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
space   = "·"
nbsp    = "⍽"
tab     = "→"
newline = "⏎"
tabpad  = "·"

[keys.insert]
C-backspace = "completion"

[keys.insert.j]
j = "normal_mode"

[keys.normal]
D = ["move_char_left", "delete_selection"]
V = ["extend_line_below", "select_mode"]
X = "select_line_above"

C-q = ":write-quit-all"

[keys.select]
D = ["move_char_left", "delete_selection"]
X = "select_line_above"

[keys.normal.g]
n = ["select_mode", "goto_line_start", "normal_mode"]
o = ["select_mode", "goto_line_end",   "normal_mode"]

[keys.select.g]
n = ["select_mode", "goto_line_start"]
o = ["select_mode", "goto_line_end"]

[keys.normal.z]
F = "page_down"
P = "page_up"
f = "scroll_down"
p = "scroll_up"

[keys.select.z]
F = "page_down"
P = "page_up"
f = "scroll_down"
p = "scroll_up"

[keys.normal.Z]
F = "page_down"
P = "page_up"
f = "scroll_down"
p = "scroll_up"

[keys.select.Z]
F = "page_down"
P = "page_up"
f = "scroll_down"
p = "scroll_up"

[keys.normal.space]
","   = "buffer_picker"
"."   = "file_picker_in_current_buffer_directory"
space = "file_picker"
tab   = "jump_backward"
S-tab = "jump_forward"

[keys.select.space]
","   = "buffer_picker"
"."   = "file_picker_in_current_buffer_directory"
space = "file_picker"
tab   = "jump_backward"
S-tab = "jump_forward"

[keys.normal.backspace]
"!"     = "shell_append_output"
"("     = "rotate_selection_contents_backward"
")"     = "rotate_selection_contents_forward"
","     = "remove_primary_selection"
"."     = "repeat_last_motion"
":"     = "ensure_selections_forward"
";"     = "flip_selections"
"_"     = "merge_consecutive_selections"
"`"     = "switch_to_uppercase"
"minus" = "merge_selections"
"|"     = "shell_pipe_to"
'*'     = 'search_selection'
C       = "copy_selection_on_prev_line"
I       = 'select_all_children'
J       = "join_selections_space"
K       = "remove_selections"
U       = "later"
c       = "change_selection_noyank"
d       = "delete_selection_noyank"
s       = "split_selection_on_newline"
u       = "earlier"
x       = "shrink_to_line_bounds"

[keys.select.backspace]
"!"     = "shell_append_output"
"("     = "rotate_selection_contents_backward"
")"     = "rotate_selection_contents_forward"
","     = "remove_primary_selection"
"."     = "repeat_last_motion"
":"     = "ensure_selections_forward"
";"     = "flip_selections"
"_"     = "merge_consecutive_selections"
"`"     = "switch_to_uppercase"
"minus" = "merge_selections"
"|"     = "shell_pipe_to"
'*'     = 'search_selection'
C       = "copy_selection_on_prev_line"
I       = 'select_all_children'
J       = "join_selections_space"
K       = "remove_selections"
U       = "later"
c       = "change_selection_noyank"
d       = "delete_selection_noyank"
s       = "split_selection_on_newline"
u       = "earlier"
x       = "shrink_to_line_bounds"

[keys.normal.backspace.backspace]
a = "increment"
c = "toggle_comments"
s = "save_selection"
x = "decrement"

[keys.select.backspace.backspace]
a = "increment"
c = "toggle_comments"
s = "save_selection"
x = "decrement"

[keys.normal."'"]
n = "select_prev_sibling"
e = "shrink_selection"
i = "expand_selection"
o = "select_next_sibling"

E = 'select_all_children'
Z = ":config-reload"
a = 'select_all_siblings'
z = ":config-open"

[keys.select."'"]
n = "select_prev_sibling"
e = "shrink_selection"
i = "expand_selection"
o = "select_next_sibling"

E = 'select_all_children'
Z = ":config-reload"
a = 'select_all_siblings'
z = ":config-open"
