theme = "catppuccin_mocha"

[editor]
auto-completion           = true
auto-format               = true
auto-info                 = true
auto-pairs                = false
auto-save                 = false
bufferline                = "never"
color-modes               = true
completion-replace        = false
completion-trigger-len    = 4
cursorcolumn              = true
cursorline                = true
idle-timeout              = 400
line-number               = "relative"
preview-completion-insert = false
rulers                    = [120]
scroll-lines              = 2
shell                     = ["fish", "-c"]
text-width                = 120
undercurl                 = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character   = "|"
render      = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages	  = true

[editor.smart-tab]
enable         = true
supersede-menu = true

[editor.soft-wrap]
enable             = true
max-indent-retain  = 40
max-wrap           = 20
wrap-at-text-width = true
wrap-indicator     = "↪"

[editor.statusline]
left      = ["file-modification-indicator", "file-name"] 
center    = ["spinner", "mode",      "spacer", "selections", "primary-selection-length",
          "spacer",  "separator", "spacer", "position",   "position-percentage", "total-line-numbers"]
right     = ["register", "diagnostics", "workspace-diagnostics"]
separator = "󰣐"

[editor.statusline.mode]
insert = "󱃱"
normal = "󰣐"
select = ""

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
space   = "·"
nbsp    = "⍽"
tab     = "→"
newline = "⏎"
tabpad  = "·"

[keys.insert.j]
j = "normal_mode"

[keys.normal]
D = ["move_char_left", "delete_selection"]

# n = "move_char_left"
# e = "move_visual_line_down"
# i = "move_visual_line_up"
# o = "move_char_right"

# N = "insert_mode"
# E = "open_below"
# I = "open_above"
# O = "insert_at_line_start"

# h = "move_next_word_end"
# l = "search_next"

# H = "move_next_long_word_end"
# L = "search_prev"

[keys.select]
D = ["move_char_left", "delete_selection"]

# n = "move_char_left"
# e = "move_visual_line_down"
# i = "move_visual_line_up"
# o = "move_char_right"

# N = "insert_mode"
# E = "open_below"
# I = "open_above"
# O = "insert_at_line_start"

# h = "move_next_word_end"
# l = "extend_search_next"

# H = "move_next_long_word_end"
# L = "extend_search_prev"

[keys.normal.g]
n = ["select_mode", "goto_line_start", "normal_mode"]
o = ["select_mode", "goto_line_end",   "normal_mode"]

[keys.select.g]
n = ["select_mode", "goto_line_start"]
o = ["select_mode", "goto_line_end"]

[keys.normal.z]
e = "scroll_down"
i = "scroll_up"

E = "page_down"
I = "page_up"

[keys.select.z]
e = "scroll_down"
i = "scroll_up"

E = "page_down"
I = "page_up"

[keys.normal.Z]
e = "scroll_down"
i = "scroll_up"

E = "page_down"
I = "page_up"

[keys.select.Z]
e = "scroll_down"
i = "scroll_up"

E = "page_down"
I = "page_up"

[keys.normal.space]
","   = "buffer_picker"
"."   = "file_picker_in_current_buffer_directory"
space = "file_picker"

[keys.select.space]
","   = "buffer_picker"
"."   = "file_picker_in_current_buffer_directory"
space = "file_picker"

[keys.normal.backspace]
c       = "change_selection_noyank"
C       = "copy_selection_on_prev_line"
d       = "delete_selection_noyank"
":"     = "ensure_selections_forward"
";"     = "flip_selections"
J       = "join_selections_space"
K       = "remove_selections"
"_"     = "merge_consecutive_selections"
"minus" = "merge_selections"
","     = "remove_primary_selection"
"."     = "repeat_last_motion"
"("     = "rotate_selection_contents_backward"
")"     = "rotate_selection_contents_forward"
"!"     = "shell_append_output"
"|"     = "shell_pipe_to"
s       = "split_selection_on_newline"
"`"     = "switch_to_uppercase"
u       = "earlier"
U       = "later"
x       = "shrink_to_line_bounds"

[keys.select.backspace]
c       = "change_selection_noyank"
C       = "copy_selection_on_prev_line"
d       = "delete_selection_noyank"
":"     = "ensure_selections_forward"
";"     = "flip_selections"
J       = "join_selections_space"
K       = "remove_selections"
"_"     = "merge_consecutive_selections"
"minus" = "merge_selections"
","     = "remove_primary_selection"
"."     = "repeat_last_motion"
"("     = "rotate_selection_contents_backward"
")"     = "rotate_selection_contents_forward"
"!"     = "shell_append_output"
"|"     = "shell_pipe_to"
s       = "split_selection_on_newline"
"`"     = "switch_to_uppercase"
u       = "earlier"
U       = "later"
x       = "shrink_to_line_bounds"

[keys.normal.backspace.backspace]
a = "increment"
c = "toggle_comments"
i = "jump_forward"
s = "save_selection"
o = "jump_backward"
x = "decrement"

[keys.select.backspace.backspace]
a = "increment"
c = "toggle_comments"
i = "jump_forward"
s = "save_selection"
o = "jump_backward"
x = "decrement"

[keys.normal."'"]
n = "select_prev_sibling"
e = "shrink_selection"
i = "expand_selection"
o = "select_next_sibling"
z = ":config-open"
Z = ":config-reload"

[keys.select."'"]
n = "select_prev_sibling"
e = "shrink_selection"
i = "expand_selection"
o = "select_next_sibling"
z = ":config-open"
Z = ":config-reload"
