(("spacemacs" . ((user-emacs-directory . "~/spacemacs")
                 (server-name . "spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))))
("doom" . ((user-emacs-directory . "~/doom-emacs")
           (server-name . "doom")
           (env . (("DOOMDIR" . "~/doom-config"))))))
