# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  theme:
    activeBorderColor:
      - '#40a02b'
      - bold
    inactiveBorderColor:
      - '#7287fd'
    selectedLineBgColor:
      - '#ccd0da'
    optionsTextColor:
      - '#179299'
  returnImmediately: true
customCommands:
  containers:
    - name: bash
      attach: true
      command: 'docker exec -it {{ .Container.ID }} bash'
      serviceNames: []
