[global/wm]
include-file = $HOME/.config/polybar/themes/mocha.ini

[section/default]
font-0 = JetBrainsMono Nerd Font:size=23:weight=bold;6
font-1 = JetBrainsMono Nerd Font:size=20;4

background   = #00
foreground   = ${colors.text}
border-color = ${colors.mantle}

height        = 32pt
padding       = 3
line-size     = 3pt
module-margin = 1

offset-y          = 0.5%
override-redirect = true
# wm-restack        = i3

cursor-click  = pointer
cursor-scroll = ns-resize

enable-ipc = true

[bar/bottom-bar]
inherit = section/default 

bottom = true

modules-left   = i3 voyager docker
modules-center = date
modules-right  = pulseaudio network battery

scroll-up   = "#i3.prev"
scroll-down = "#i3.next"

[bar/top-bar]
inherit = section/default 

modules-left  = menu-commands
modules-right = cpu memory temperature

cursor-scroll = ns-resize

[module/i3]
type = internal/i3

strip-wsnumbers = true
fuzzy-match     = false

ws-icon-0       = 1: 1;
ws-icon-1       = 2: 2;
ws-icon-2       = 3: 3;
ws-icon-3       = 4: 4;
ws-icon-4       = 5: 5;
ws-icon-5       = 6: 6;󰌌
ws-icon-default = 󰓩

format = <label-state>

label-focused   = %{F#313244}%{B#313244}%{F#89b4fa} %icon% %{B#00}%{F#313244} %{B-}%{F-}
label-unfocused = %{F#181825}%{B#181825}%{F#a6adc8} %icon% %{B#00}%{F#181825} %{B-}%{F-}
label-visible   = %{F#181825}%{B#181825}%{F#a6adc8} %icon% %{B#00}%{F#181825} %{B-}%{F-}
label-urgent    = %{F#313244}%{B#313244}%{F#94e2d5} %icon% %{B#00}%{F#313244} %{B-}%{F-}

[module/date]
type = internal/date

interval = 1

date     = %d/%m/%Y %H:%M:%S
date-alt = %H:%M

format = <label>

label = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %date%%{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/voyager]
type = custom/script

exec = fish -c voyager_get_layer

interval = 0.3

label = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %output% %{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/docker]
type = custom/script

exec = docker ps -q | wc -l

interval = 1

label = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %output% %{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/menu-commands]
type = custom/menu

expand-right = true

menu-0-0      = %{F#89b4fa} %{B#89b4fa}%{F#11111b} 󰪯 %{B#00}%{F#89b4fa}%{B-}%{F-}
menu-0-0-exec = #menu-commands.open.1

menu-0-1      = %{F#89b4fa} %{B#89b4fa}%{F#11111b}  %{B#00}%{F#89b4fa}%{B-}%{F-}
menu-0-1-exec = #menu-commands.open.2

menu-1-0      = %{F#89b4fa} %{B#89b4fa}%{F#11111b}  %{B#00}%{F#89b4fa}%{B-}%{F-}
menu-1-0-exec = alacritty -e fish -c 'edgar down && sleep 3s'

menu-1-1      = %{F#89b4fa} %{B#89b4fa}%{F#11111b} 󰚰 %{B#00}%{F#89b4fa}%{B-}%{F-}
menu-1-1-exec = alacritty -e fish -c 'edgar update-projects && sleep 3s'

menu-2-0      = %{F#89b4fa} %{B#89b4fa}%{F#11111b} 󰚰 %{B#00}%{F#89b4fa}%{B-}%{F-}
menu-2-0-exec = alacritty -e fish -c 'sudo apt update && sudo apt upgrade && sleep 3s'

menu-2-1      = %{F#89b4fa} %{B#89b4fa}%{F#11111b} 󰿞 %{B#00}%{F#89b4fa}%{B-}%{F-}
menu-2-1-exec = alacritty -e fish -c 'sudo apt autoclean && sudo apt autopurge && sudo apt autoremove && sudo apt clean && sleep 3s'

label-open  = %{F#89b4fa}%{B#89b4fa}%{F#11111b}  %{B#00}%{F#89b4fa}%{B-}%{F-}
label-close = %{F#89b4fa}%{B#89b4fa}%{F#11111b}  %{B#00}%{F#89b4fa}%{B-}%{F-}

[module/pulseaudio]
type = internal/pulseaudio

label-volume = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󰝚 %{B#181825}%{F#a6adc8}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}
label-muted  = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󰝛 %{B#181825}%{F#45475a}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/network]
type = internal/network

interface = wlp0s20f3

label-connected    = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󰣺 %{B#181825}%{F#a6adc8}%{T2} %essid% %netspeed:9% %{B#00}%{F#181825}%{T1}%{B-}%{F-}
label-disconnected = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󰣼 %{B#181825}%{F#a6adc8}%{T2} Disconnected %{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/battery]
type = internal/battery

full-at = 100

label-charging    = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󰂅 %{B#181825}%{F#a6adc8}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}
label-discharging = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󰢝 %{B#181825}%{F#a6adc8}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}
label-full        = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󱈏 %{B#181825}%{F#a6adc8}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}
label-low         = %{F#89b4fa}%{B#89b4fa}%{F#11111b}󱃍 %{B#181825}%{F#a6adc8}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/cpu]
type = internal/cpu

interval = 2

label = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %percentage:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/memory]
type = internal/memory

interval = 2

label = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %percentage_used:3%%%{B#00}%{F#181825}%{T1}%{B-}%{F-}

[module/temperature]
type = internal/temperature

interval  = 0.5
zone-type = x86_pkg_temp

label      = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %temperature-c%%{B#00}%{F#181825}%{T1}%{B-}%{F-}
label-warn = %{F#89b4fa}%{B#89b4fa}%{F#11111b} %{B#181825}%{F#a6adc8}%{T2} %temperature-c%%{B#00}%{F#181825}%{T1}%{B-}%{F-}

[settings]
screenchange-reload = true
pseudo-transparency = true
